CACHE_CONFIG={
  'CACHE_TYPE': 'redis',
  'CACHE_KEY_PREFIX' :'fcache',
  'CACHE_REDIS_HOST':'$APP_CACHE_HOST',
  'CACHE_REDIS_PORT':'$APP_CACHE_PORT',
  'CACHE_REDIS_URL':'redis://$APP_CACHE_AUTH$APP_CACHE_HOST:$APP_CACHE_PORT'
}


