# -*- coding: utf-8 -*-

from setuptools import find_packages, setup

version = '1.0.0'

setup(name='ge.bpmc',
      version=version,
      description='BPM Cloud',
      url='',
      author='Julien Stegle',
      author_email='julien.stegle@ge.com',
      license='Proprietary',
      classifiers=[
          'Development Status :: 2 - Pre-Alpha',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: Implementation :: CPython',
          'Intended Audience :: Healthcare Industry',
          'Topic :: Scientific/Engineering :: Information Analysis',
          'Operating System :: OS Independent',
          'License :: Other/Proprietary License',
      ],
      packages=find_packages(exclude=['ez_setup']),
      namespace_packages=['ge'],
      include_package_data=True,
      zip_safe=False,
      install_requires=[
          'SQLAlchemy==1.1.15',
          'webdavclient3==0.5',
          'PyMySQL==0.7.11',
          'Flask==0.12.2',
          'Flask-Cors==3.0.3',
          'Flask-RESTful==0.3.6',
          'flask-restful-swagger-2==0.35',
          'flask-swagger-ui==3.6.0',
          'dict2xml==1.5',
          'dependency_injector==3.11.1',
          'celery==4.1.0',
          'PyYAML==3.12',
          'multiprocess==0.70.5',
          'eventlet==0.22.0',
          'matplotlib==2.1.0',
          'numpy==1.13.3',
          'scipy==1.0.1',
          'scikit-image==0.13.1',
          'scikit-learn==0.19.1',
          'pandas==0.21.0',
          'amqp==2.2.2',
          'aniso8601==3.0.0',
          'billiard==3.5.0.3',
          'certifi==2018.4.16',
          'chardet==3.0.4',
          'dependency-injector==3.11.1',
          'dict2xml==1.5',
          'dill==0.2.7.1',
          'enum34==1.1.6',
          'eventlet==0.22.0',
          'greenlet==0.4.13',
          'idna==2.6',
          'itsdangerous==0.24',
          'kombu==4.1.0',
          'lxml==4.2.1',
          'multiprocess==0.70.5',
          'networkx==2.1',
          'python-dateutil==2.7.3',
          'pytz==2018.4',
          'PyWavelets==0.5.2',
          'PyYAML==3.12',
          'requests==2.18.4',
          'six==1.11.0',
          'urllib3==1.22',
          'vine==1.1.4',
          'webdavclient3==0.5',
          'Werkzeug==0.14.1'
      ],
      extras_require={
          'test': ['mockito==1.0.12'],
      },)
