#!/usr/bin/env python3
# encoding: utf-8
"""
python script for rosalind problem
"""
from collections import Counter


def dna_count(file):
    f = open(file, 'r')
    dataset = f.read()
    c = Counter(dataset)
    print(str(c['A']) + "  " + str(c['C']) + "  " + str(c["G"]) + "  " + str(c["T"]))


def dna_to_rna(file):
    f = open(file, 'r')
    dataset = str(f.read())
    newdata = dataset.replace('T', 'U')
    return newdata


def dna_reverse_comp(dataset):
    complements = {'A': 'T', 'C': 'G', 'T': 'A', 'G': 'C'}

    sc = reversed(dataset)
    sc = [complements[c] for c in sc]

    return ''.join(sc)


if __name__ == "__main__":
    dna_count("/home/arnaud/Desktop/dna.txt")
    print(dna_to_rna("/home/arnaud/Desktop/dna.txt"))
    print(dna_reverse_comp("GGCCTTCATAAAGAGTCGACGTGCCCTCGAGACCCGCCATACCCGAGACGTCTAGAGTGATATCGTACGAACATATGAGGGCAAGCCACATCCCAGCTCAATCTGTGTACTTGTAATTGACATAATCAGCAGTAACAGTATGTAGGCCGGGGCGTTCGCAGTAGGTTTCACATTTCACAACCGACTTTGCCCGTGGCAGTTTACCTATTGTCCTTCGCTGACTATAGTTAAACGCGCGTATAGCGATCAAGCTACGGGGGCAACCAACTTCACAGCATTAGCACTACCACCTGATTGTGTACTCGTCTTACAAGAACGTACACGAGACGTTTACACCAGTATTAAGAAACCACTTCGAATGATGTCTTCATGTTTCTGATTACTACTATTTGTCGCCTCGCTTTGCAGTCTAATTGATAGACTGTTTCCAAAACGACTATCGCACTGGTGCACACCTACGCCTAACGTGACGCAACCGCCCGTTTCGTATGCAATAATGGGCAAAGCATATACTCCTGCCGTGCCAGCACCGTTGCCAGGTCCCATGCCTGGTCGCATGGCTTTCGAGACTTGTGGCTCTTTAGAAACGCGGTGCTTCCACACTTCACGGAGCGGCACGACTGTCTACGGGTTCCGACAAGGGAAGCAATTCAGGATCCCCACCGGATAGTGCGTACTTGGTACCACTCATATAGTAAGTGGGTACAGCTTATTGGATGGATAGCGCTCTAGTACCCAGGTGTAGGAACTCGCGGACGACTTACTAATATACGCACGAGTGCAGGCCTGTTCATTCCTGGCGTTAAATCGACGGCCTATTATTTATATTGAGTCTATAAATATCGGAGGCACGGAGTGATCTTCAAAGCCAAGGTTGCTATAACCGGGTGGAGTCCGTGGTAAGGTACGTGGCAGCAGGCACCTGGGTCCCTGA"))