version: '1'

services:
  haproxy:
    image: haproxy:1.8-alpine
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
    ports:
     - '8080:8080'

  nginx1:
    image: nginx:stable-alpine
    volumes:
      -type: bind
      source: nginx/index1.html
      target: /usr/share/nginx/html/index/html

