CREATE DATABASE IF NOT EXISTS superset COLLATE 'utf8_general_ci';
GRANT ALL ON superset.* TO 'superset'@'localhost' IDENTIFIED BY '$APP_SUPERSET_PASSWORD' WITH GRANT OPTION;
GRANT ALL ON superset.* TO 'superset'@'%' IDENTIFIED BY '$APP_SUPERSET_PASSWORD' WITH GRANT OPTION;
FLUSH PRIVILEGES;
